myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.conf.urls import handler404


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('userhome.urls')),
    path('adminhome/', include('adminhome.urls')),
    path('shop/', include('shop.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

# handler400 = 'userhome.views.error_404'

shop/urls.py
from . import views
from django.urls import path
                                            
urlpatterns = [
    path('', views.viewcart, name="viewcart"),
    path('addtocart/<int:varient_id>/', views.addtocart, name='addtocart'),
    #plus cart using ajax
    # path('pluscart/', views.plus_cart,name='pluscart'),
    path('addcartitem/<int:product_id>/<int:varient_id>/',views.addcartitem,name='addcartitem'),
    path('removecartitem/<int:product_id>/<int:varient_id>/',views.removecartitem,name='removecartitem'),
    path('removecartproduct/<int:product_id>/<int:varient_id>/',views.removecartproduct,name='removecartproduct'),

    #wishlist urls 
    path('wishlist/',views.userwishlist,name='userwishlist'),
    path('addwishlist/<int:varient_id>/',views.add_to_wishlist,name='add_to_wishlist'),
    path('removewishlist/<int:varient_id>/',views.remove_from_wishlist,name='remove_from_wishlist'),

    path('checkout/',views.checkout,name='checkout'),
    path('orderconfirm/',views.confirm_order,name='orderconfirm'),
    path('sendmails/',views.sendmails, name='sendmail'),
    path('placeorder/',views.placeOrder,name='ordersuccess'),
    path('ordercomplete/',views.orderComplete,name="ordercomplete"),
    path('proceed_to_pay/',views.razorPayCheck,name="razorpaycheck"),
]

adminhome/models.py
from django.db import models


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    image = models.ImageField(upload_to='category',null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name




    
class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.PositiveBigIntegerField(null=True)
    # stock = models.PositiveIntegerField(null=True)
    updated = models.DateField(auto_now=True)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

class ProductVarient(models.Model):
    varientname = models.CharField(max_length=100,null=True)
    varstock = models.PositiveIntegerField(null=True)
    # varprice = models.PositiveIntegerField(null=True)
    proname = models.ForeignKey(Product, related_name='variants',on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.proname} / {self.varientname}"






    
class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    images = models.ImageField(upload_to='media',null=True)


    def __str__(self):
        return self.product.name
    

    

    
    

userhome/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
# Create your models here.



STATE_CHOICES = (
    ('Kerala','Kerala'),
    ('Tamilnadu','Tamilnadu'),
    ('Karnataka','Karnataka'),
    ('AndraPradesh','AndraPradesh')
)
DIST_CHOICES = {
    ('Kannur','Kannur'),
    ('Kozhikkode','Kozhikkode'),
    ('Ernakulam','Ernakulam'),
    ('Thiruvananthapuram','Thiruvananthapuram'),
    ('Banglore','Banglore'),
    ('Hubli','Hubli'),
    ('Hydrabad','Hydrabad'),
    ('Coimbator','Coimbator'),
    ('Madurai','Madurai'),
}

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    mobile_regex = RegexValidator(regex=r'^\d+$', message="Mobile number should only contain digits")
    mobile = models.CharField(validators=[mobile_regex], max_length=10 ,null=True)
    address = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='user', null=True, blank=True)
    district = models.CharField(choices=DIST_CHOICES,max_length=20, null=True, blank=True)
    state = models.CharField(choices=STATE_CHOICES,max_length=20, null=True)
    pincode_regex = RegexValidator(regex=r'^\d+$', message="Pincode should only contain digits")
    pincode = models.PositiveIntegerField(null=True, blank=True)
    otp = models.CharField(max_length=6, null=True, blank=True)
    is_verified = models.BooleanField(default=False)
    is_blocked = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username








class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    firstname = models.CharField(max_length=100,null=True)
    lastname = models.CharField(max_length=100,null=True)
    email = models.EmailField(max_length=200)
    address_line_1 = models.CharField(max_length=255)
    address_line_2 = models.CharField(max_length=255, blank=True)
    phone_regex = RegexValidator(regex=r'^\d+$', message="Mobile number should only contain digits")
    phone = models.CharField(validators=[phone_regex], max_length=10, null=True)
    city = models.CharField(choices=DIST_CHOICES,max_length=255)
    state = models.CharField(choices=STATE_CHOICES,max_length=255)
    pincode_regex = RegexValidator(regex=r'^\d+$', message="Pincode should only contain digits")
    pincode = models.PositiveIntegerField(null=True,blank=True)

    def __str__(self):
        return self.user.username
        


class Banner(models.Model):
    image = models.ImageField(upload_to='banner')
    title = models.CharField(max_length=300,null=True)
    desc = models.CharField(max_length=200)



 
    

templates/add_address.html
{% extends 'userprofile.html' %}
{% load static %}
{% block profile %}
<section class="section-content">
    

<article class="card">
            <br/>
<h2>&nbsp;&nbsp;Add New Address</h2>
            <div class="card-body">

                <div class="row">
                    <div class="col-md-12">
                        <form class="row contact_form" action="" method="POST">
                            {%csrf_token%}
                            <div class="col-md-6 form-group p_star">
                                <label>First Name</label>
                                <input type="text" class="form-control" id="first"  name="firstname" placeholder="First Name"required />
                            </div>
                            <div class="col-md-6 form-group p_star">
                                <label>Last Name</label>
                                <input type="text" class="form-control" id="last"  name="lastname" placeholder="Last Name" required/>
                            </div>
                            <div class="col-md-6 form-group p_star">
                                <label>Phone Number</label>
                                <input type="text" class="form-control" id="phone"  name="phone"  placeholder="Phone Number"required  pattern="[0-9]+" title="Please enter only digits" minlength="10" maxlength="10"/>
                            </div>
                            <div class="col-md-6 form-group p_star">
                                <label>Email</label>
                                <input type="email" class="form-control" id="email"  name="email"placeholder="Email" required/>
                            </div>
                            <div class="col-md-6 form-group p_star">
                                <label>Address</label>
                                <input type="text" class="form-control" id="add1"  name="address_line_1" placeholder="Address"required/>
                            </div>
                            <div class="col-md-6 form-group p_star">
                                <label>Landmark</label>
                                <input type="text" class="form-control" id="add1"  name="address_line_2" placeholder="Landmark"required/>
                            </div>
                            
                            <div class="col-md-6 form-group p_star">
                                <label>City</label><br>
                                <select class="form-select" id="id_city" name="city" required><br>
                                    <option value="">Select city</option>
                                    {% for city in city %}
                                        
                                            <option value="{{ city }}">{{ city }}</option>
                                        
                                    {% endfor %}
                                </select><br>
                            </div>
                            <div class="col-md-6 form-group p_star">
                                <label>State</label><br>
                                <select class="form-select" id="id_state" name="state" required><br>
                                    <option value="">Select State</option>
                                    {% for state in state %}
            
                                            <option value="{{ state }}">{{ state }}</option>
        
                                    {% endfor %}
                                </select><br>
                            </div>
                            <div class="col-md-6 form-group">
                                <label>Pin Code</label>
                                <input type="text" class="form-control" id="pincode" name="pincode"  placeholder="Pincode" required pattern="[0-9]+" title="Please enter only digits" minlength="6" maxlength="6"/>
                            </div>
                            <input type="hidden" class="form-control" name="form_from" value="{{form_from}}" required/>


                            <br/><br/>
                            <div class="col-sm-12 form-group p_star">
                                <center>
                                    <button type="submit" name="submit" class=" btn btn-info " style="height:50px">Save</button>
                                </center>
                            </div>
                        </form>
                    </div>

                    </div>

                </div>
            </div>
        </article>

    </main>
    </div>
    </div>
</section>

{% endblock %}

templates/address_book.html
{% extends 'userprofile.html' %}
{% load static %}
{% block profile %}
<form method="POST">
    {% csrf_token %}
<div class="container">
    <div class="card shadow">
        <div class="card-body"> 
           <h5 class="p-2 text-danger" style="border-bottom: 2px solid orange;">Saved Addresses</h5>
            <div class="container">
                <a href="{% url 'add_address' 1 %}" class="btn btn-success my-4">Add Address</a>
                {% for address in addresses %}
                <div class="container">
                    <div class="card shadow my-2 col-lg-6">
        
                        <div class="card-body"> 
                            {% comment %} <input type="checkbox" name="selected_addresses" value="{{ address.id }}"> {% endcomment %}
                            <div class="container">
                                <p>{{ address.firstname }}  {{ address.lastname }}</p>
                                <p>{{ address.phone }}</p>
                                <p>{{ address.email }}</p>
                                <p>{{ address.address_line_1 }}</p>
                                <p>{{ address.address_line_2 }}</p>
                                <p>{{ address.city }} , {{ address.state }}</p>  
                                <p>{{ address.pincode }}</p>
                                <a href="{% url 'edit_address' address.id %}" class="btn btn-info mt-5">Edit</a>
                               <a href="{% url 'delete_address' address.id %}" class="btn btn-danger mt-5" onclick="confirmDelete(event)">Delete</a> 
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                
                
                {% comment %} <input type="submit" class="btn btn-danger mt-5"  value="Delete"> {% endcomment %}
                

   {% comment %} <a href="document.pdf" download>Download PDF</a> {% endcomment %}
            </div>
        </div>
    </div>
</div>
</form>

<script>
    function confirmDelete(event) {
        event.preventDefault(); // prevent the link from redirecting immediately
        alertify.confirm('Message', 'Are You Sure Want to Delete This', function(){
            window.location.href = event.target.href; // redirect to the delete URL
        }, function(){ 
            alertify.error('Cancel')
        });
    }
</script>
{% endblock %}

templates/changepassword.html
{% extends 'userprofile.html' %}
{% load static %}
{% block profile %}

<div class="card shadow col-sm-8">
    <div class="card-body">
        <h5 class="p-2 text-danger" style="border-bottom: 2px solid orange;">Change Password</h5>
        <div class="container-fluid">
            <form method="POST" action="">
                {% csrf_token %}
                <div class="form-row">
 
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Current Password</label>
                            <input type="password" name="currentpassword" id="currentpassword" placeholder="Enter Current Password"  class="form-control" required>
                        </div>
                    </div>
                </div>
 
                <div class="form-row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>New Password</label>
                            <input type="password" name="newpassword" placeholder="Enter New Password"  class="form-control" required>
                        </div>
                    </div>
                </div>
 
                <div class="form-row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Confirm New Password</label>
                            <input type="password" name="confirmpassword" id="confirmpassword" placeholder="Confirm New Password Again"  class="form-control" required>
                        </div>
                    </div>
 
                </div>
                <input type="submit" value="Submit" class="m-2 px-3 btn btn-primary">
            </form>
        </div>
    </div>
</div>


{% endblock %}

templates/edit_address.html
{% extends 'userprofile.html' %}
{% load static %}
{% block profile %}
<div class="container">
    <div class="card shadow col-sm-8">
        <div class="card-body"> 
           <h5 class="p-2 text-danger" style="border-bottom: 2px solid orange;">Edit Your Addresses</h5>
            <div class="container">
                <form method="post">
                    {% csrf_token %}

                    <div class="form-group">
                        <label for="firstname">First Name:</label>
                        <input type="text" name="firstname" class="form-control"  value="{{ newaddress.firstname }}" required>
                    </div>
                    <div class="form-group">
                        <label for="lastname">Last Name:</label>
                        <input type="text" name="lastname" class="form-control"  value="{{ newaddress.lastname }}" required>
                    </div>
                    <div class="form-group">
                        <label for="phone">Phone:</label>
                        <input type="text" name="phone" class="form-control"  value="{{ newaddress.phone }}" minlength="10" maxlength="10" required>
                    </div>
                    <div class="form-group">
                        <label for="email">Email:</label>
                        <input type="text" name="email" class="form-control"  value="{{ newaddress.email }}" required>
                    </div>
                    <div class="form-group">
                        <label for="address_line_1">Address:</label>
                        <input type="text" name="address_line_1" class="form-control"  value="{{ newaddress.address_line_1 }}" required>
                    </div>
                    <div class="form-group">
                        <label for="address_line_2">Landmark:</label>
                        <input type="text" name="address_line_2" class="form-control"  value="{{ newaddress.address_line_2 }}" required>
                    </div>
                    <label for="city">City:</label>
                    <div class="form-group">
                        <select class="form-select col-sm-12" id="id_city" name="city" required><br>
                            <option value="">Select city</option>
                            {% for s_city in city %}
                                {% if s_city == newaddress.city %}
                                    <option value="{{ s_city }}" selected >{{ s_city }}</option>
                                {% else %}
                                    <option value="{{ s_city }}">{{ s_city }}</option>
                                {% endif %}
                            {% endfor %}
                        </select><br>
                        
                    </div><br>
                    <label for="state">State:</label>
                    <div class="form-group">
                        
                        <select class="form-select col-sm-12" id="id_state" name="state" required><br>
                            <option value="">Select State</option>
                            {% for s_state in state %}
                                {% if s_state == newaddress.state %}
                                <option value="{{ s_state }}" selected >{{ s_state }}</option>
                                {% else %}
                                    <option value="{{ s_state }}">{{ s_state }}</option>
                                {% endif %}
                            {% endfor %}
                        </select><br>
                        
                    </div><br>
                    
                    <div class="form-group">
                        <label for="pincode">Pincode:</label>
                        <input type="text" name="pincode" value="{{ newaddress.pincode}}" class="form-control col-4" required  pattern="[0-9]+" title="Please enter only digits" minlength="6" maxlength="6">
                    </div>
                    {% comment %} <input type="select" name="state" required><br> {% endcomment %}
                
                    
                
                    <input type="submit" value="Save" class="btn btn-success">
                </form>
                
                
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/user_product.html
{% extends 'home.html' %}
{% load static %}


{% block banner %}  
    <!-- breadcrumb start-->
    <section class="breadcrumb breadcrumb_bg">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="breadcrumb_iner">
                        <div class="breadcrumb_iner_item">
                            <h2>Shop Category</h2>
                            <p>Home <span>-</span> Shop Category</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb end-->

{% endblock %}
{% block bodies %}
    <!--================User Product Area =================-->
    <section class="cat_product_area section_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="left_sidebar_area">
                        <aside class="left_widgets p_filter_widgets">
                            <div class="widgets_inner">
                                <ul class="list">
                                    <li>
                                        <a href="{% url 'userproduct' 0 %}">All Categories</a>
                                    </li>
                                    {% for category in allcategory %}
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle text-dark bg-light" href="{% url 'userproduct' category.id %}" id="navbardrop" data-bs-toggle="dropdown" aria-expanded="false">
                                            <i class="fas fa-chart-bar mr-3 text-primary fa-fw"></i> {{ category.name }}
                                        </a>
                                        {% comment %} <div class="dropdown-menu">
                                            {% for varient in category.productvarient_set.all %}
                                            <a class="dropdown-item" href="{% url 'userproduct' category.id %}?varientid={{ varient.id }}">{{ varient.varientname }}</a>
                                            {% endfor %}
                                        </div> {% endcomment %}
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </aside>

                    </div>
                </div>
                <div class="col-lg-9">
                    {% comment %} <div class="row">
                        <div class="col-lg-12">
                            <div class="product_top_bar d-flex flex-row-reverse">
                                <div class="single_product_menu d-flex">
                                   <form method="GET" action="{% url 'search' %}">
                                    <div class="input-group">
                                        <input type="search" class="form-control" placeholder="search" aria-describedby="inputGroupPrepend" name="keyword">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text" id="inputGroupPrepend"><button type="submit"><i class="fa fa-search"></i></button></span>
                                        </div>
                                    </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div> {% endcomment %}

                    <div class="row align-items-center latest_product_inner">
                        {% for j in page_obj %}
                        <div class="col-lg-4 col-sm-6">
                            <div class="single_product_item">
                                
                                <a href="{% url 'singleproduct' j.id %}"> <img src="{{ j.productimage_set.first.images.url }}" class="img-fluid" alt=""></a>
                                
                                <div class="single_product_text">
                                    <h4 class="text-center">{{ j.name }}</h4>
                                    <h3 class="text-center"> {{ j.price }}</h3>
                                    {% comment %} <ul class="d-flex  justify-content-between">
                                        <li><a href="{% url 'singleproduct' j.id %}"><i class="fa fa-eye"></i></a></li>
                                        <li><a href="{% url 'add_to_wishlist' j.id %}"><i class="fa fa-heart"></i></a></li> 
                                        {% if j.stock == 0 %}
                                        <li><a ><i class="">Out of Stock</i></li>
                                        {% else %} 
                                        <li><a href="{% url 'addtocart' j.id %}"><i class="fa fa-shopping-cart"></i></li> 
                                        {% endif %} 
                                    </ul> {% endcomment %}
                                    {% comment %} <a href="{% url 'singleproduct' j.id %}">view more</a>
                                    <a href="#" class="add_cart">+ add to cart<i class="ti-heart"></i></a> {% endcomment %}
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        
                        
                        <div class="col-lg-12 ">
                            <div class="pagination justify-content-center">
                                <nav aria-label="Page navigation example">
                                    <ul class="pagination justify-content-center">
                                        {% if page_obj.has_previous %}
                                            <li class="page-item">
                                                <a class="page-link" href="?page=1" aria-label="First">
                                                    <i class="ti-angle-double-left"></i>
                                                </a>
                                            </li>
                                            <li class="page-item">
                                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                                    <i class="ti-angle-left"></i>
                                                </a>
                                            </li>
                                        {% endif %}
                                        {% for page in page_obj.paginator.page_range %}
                                            {% if page_obj.number == page %}
                                                <li class="page-item active"><a class="page-link" href="#">{{ page }}</a></li>
                                            {% elif page > page_obj.number|add:'-3' and page < page_obj.number|add:'3' %}
                                                <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
                                            {% endif %}
                                        {% endfor %}
                                        {% if page_obj.has_next %}
                                            <li class="page-item">
                                                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                                    <i class="ti-angle-right"></i>
                                                </a>
                                            </li>
                                            <li class="page-item">
                                                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                                                    <i class="ti-angle-double-right"></i>
                                                </a>
                                            </li>
                                        {% endif %}
                                    </ul>
                                </nav>
                            </div>
                        </div>
                      
                        
                       
                        {% comment %} <div class="col-lg-12">
                            <div class="pageination">
                                <nav aria-label="Page navigation example">
                                    <ul class="pagination justify-content-center">
                                        {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a class="page-link" href="#" aria-label="Previous">
                                                <i class="ti-angle-double-left"></i>
                                            </a>
                                        </li>
                                        {% endif %}
                                        <li class="page-item"><a class="page-link" href="#">{{page_obj.number}}</a></li>
                                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                                        <li class="page-item"><a class="page-link" href="#">4</a></li>
                                        <li class="page-item"><a class="page-link" href="#">5</a></li>
                                        <li class="page-item"><a class="page-link" href="#">6</a></li>
                                        {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a class="page-link" href="#" aria-label="Next">
                                                <i class="ti-angle-double-right"></i>
                                            </a>
                                        </li>
                                        {% endif %} 
                                    </ul>
                                </nav>
                            </div>
                        </div> {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================End User Product Area =================-->


{% endblock %}

templates/varient.html
<button class="btn btn-primary mx-5" type="submit">Add to Cart</button>
<a href="{% url 'add_to_wishlist' varient.id %}" class="like_us"> <i class="ti-heart"></i> </a>